### ISSUE TITLE
Can you provide the evaluation code?

### ISSUE THREAD

**Issue by Seunggyu-Lee** [WU-CVGL/BAD-Gaussians#11]
Thank you for your great work!

I successfully ended the training procedure from your code, but I don't know how to calculate metrics from your paper such as PSNR.. etc (Cause I'm noob)

Can you provide the evaluation code? 

Thanks

**Comment by LingzheZhao** [comment]
Hi, thank you for your interest in our work! The tensorboard logging was enabled by default in the README, thus you can run tensorboard to see the metrics and images with

```sh
# under the same working directory when training
tensorboard --logdir outputs
```

then you can open tensorboard at http://localhost:6006/

BTW, instead of tensorboard, you can also use wandb, by changing the `--vis viewer+tensorboard` argument to `--vis viewer+wandb`.

We have two types of evaluations in our paper: deblurring and novel view synthesis, and you can evaluate deblurring metrics on synthetic datasets as described above. For novel-view synthesis, I'm currently busy with some other projects and my PhD application thus have little time to refactor the code (details were also discussed in #3). I should be free at the end of May. Please stay tuned!

Finally, in our paper, to ensure consistency (to avoid inconsistencies across different codebases caused by different implementations of PSNR/SSIM/LPIPS), we use the saved images in the `outputs` folder to evaluate the final metrics with the evaluation code in *BAD-NeRF* - We only used the metrics in tensorboard/wandb as a convenient reference when debugging.

**Comment by Seunggyu-Lee** [comment]
Thank you so much for your response! Your clear explanation helped me understand perfectly. I appreciate your taking the time to reply so promptly despite your busy schedule. I sincerely hope that your other projects go well, and I wish you the best of luck! Thank you again.
