### ISSUE TITLE
Regarding evaluation scripts independent of the nerfstudio framework

### ISSUE THREAD

**Issue by xiaoyaolovlife** [WU-CVGL/BAD-Gaussians#27]
On the Deblurf NeRF Real Motion Blur dataset（Blur Coffee）, the NVS performance initially improves and then declines. Is this behavior reasonable?
2999 28.36 
6999 30.76
9999 31.84
14999 31.89
19999 31.20

**Comment by xiaoyaolovlife** [comment]
Furthermore， Why is it necessary to freeze the scene parameters first, then apply random perturbations to the evaluation pose, and set up eval_pose_optimizer and scheduler? Why can't we directly use the intermediate camera poses from the training process as the NVS results? Thank you！

**Comment by LingzheZhao** [comment]
> On the Deblurf NeRF Real Motion Blur dataset（Blur Coffee）, the NVS performance initially improves and then declines. Is this behavior reasonable? 2999 28.36 6999 30.76 9999 31.84 14999 31.89 19999 31.20

Hi @xiaoyaolovlife, this can happen since the 3DGS training process will overfit the training views, the quality of the novel views are not guaranteed to be monotonically increasing. In some cases, some floaters may appear and they will break the novel views.

What's more, in our cases, given blurry input, the initial camera poses are inaccurate. This is also related to your second question:

> Furthermore， Why is it necessary to freeze the scene parameters first, then apply random perturbations to the evaluation pose, and set up eval_pose_optimizer and scheduler? Why can't we directly use the intermediate camera poses from the training process as the NVS results? Thank you！

In the NVS evaluation of BAD-NeRF and BAD-Gaussians, the initial camera poses are inaccurate because of the blurry inputs. Thus, in order to assess the reconstructed scene with NVS evaluation, we need to optimize the poses (find the exact camera pose that took the photo) while freezing the 3DGS scene.

Also, because they are NVS images, they are not accessible during training, thus their poses are not optimized during training. That's why we need to set up `eval_pose_optimizer` in `eval_with_pose_opt()`.

**Comment by xiaoyaolovlife** [comment]
I understand! Many thanks!
